# For Non-Admin Routes
controllers:
    resource:
        path: '../src/Controller/Public'
        namespace: 'App\Controller\Public'
    type: attribute


# For Admin Routes
admin_routes:
    resource:
        path: '../src/Controller/Admin'
        namespace: 'App\Controller\Admin'
    type: attribute
    prefix: '/admin'
    name_prefix: 'admin_'